epics-base/pvDataCPP

- src/factory/FieldCreateFactory.cpp
More informative error messages when creating type information objects (as suggested by @arkilic).  These also seem like good candidates to include stack traces as they shouldn't be encountered in well behaved code.
> Friendlier exception messages w/ stack trace during Field creation

- src/factory/PVStructure.cpp
- src/pv/pvData.h
- testApp/pv/testPVData.cpp
Access to sub-fields of a structure with exceptions thrown if this is not possible. Addresses #2.
Replaces findSubField() with private method PVStructure::GetAsImpl(), which uses char* instead of std::string to avoid temporary allocations.  Loops instead of recursing.  Also, uses exception messages to give some hint about why the lookup fails.
> Add PVStructure::getAs<>()

- documentation/RELEASE_NOTES.md
- documentation/pvDataCPP.html
- documentation/pvDataCPP_20150623.html
- src/factory/PVStructure.cpp
- src/pv/pvData.h
- testApp/pv/testPVData.cpp
API proposal to replace getAs introduced in https://github.com/epics-base/pvDataCPP/pull/4 with throwing version of getSubField called getSubFieldT as per the AI assigned to me in the EPICS V4 working group meeting 20150630.
Summary of changes:
<ol>
<li>getSubField implemented without throwing and catching an exception</li>
<li>Exception messages improved</li>
<li>Unit tests added</li>
<li>getAs renamed getSubFieldT</li>
<li>Make overloads of getSubField and getSubFieldT match</li>
<li>getSubFieldT returns a shared_ptr instead of a reference.</li>
</ol>
<p>Each of these have been done as a separate commit. <p>
<p>(Note the bug in getAs implementation was fixed in master first.)<p>
<ol>
<li>The getAs pull request  https://github.com/epics-base/pvDataCPP/pull/4 implemented getSubField by …
> GetSubFieldT

- src/factory/StandardPVField.cpp
- src/property/pvEnumerated.cpp
- src/pv/pvData.h
- testApp/copy/testPVCopy.cpp
- testApp/pv/testOperators.cpp
- testApp/pv/testPVData.cpp
<p>Calls of the deprecated function PVStructure::getScalarArrayField have been replace by calls of the template function PVStructure::getSubField.
</p>
<p>getScalarArrayField  is now declared using the USAGE_DEPRECATED macro.</p>
> Replace calls of deprecated PVStructure::getScalarArrayField

- testApp/pv/testPVData.cpp
```
../../testApp/pv/testPVData.cpp:549:14: error: use of overloaded operator '!='
is ambiguous (with operand types 'PVIntPtr' (aka 'shared_ptr<PVInt>') and
'long')
testOk1(a!=NULL);
~^ ~~~~
```
If there's a better (more standard C++) solution I'd be happy to hear it.
> Fix build problem on Mac

- src/pv/pvData.h
<p>Move definitions of 2 getSubFieldT overloads:</p>
<ol>
<li>shared_ptr<PVT> PVStructure::getSubFieldT(const char *name) const
<li>shared_ptr<PVT> PVStructure::getSubFieldT(size_t fieldOffset) const
</ol>
<p>out of function body so not implicitly inlined.</p>
<p>Implementation now uses stringstream. Moving outside class to avoid code bloat.</p>
> Move getSubFieldT definitions out of class body

- src/factory/FieldCreateFactory.cpp
- testApp/copy/testCreateRequest.cpp
- testApp/pv/testPVData.cpp
Check for invalid characters in field names (eg '.') as they are created.  Restrict character set to ascii alpha numeric and '_' (can extend later).
> validate field names

- src/misc/byteBuffer.h
Check for allocation failure in ctors and add const qualifier where possible.  Also document that externally provided buffers will be passed to free() (so can't use new[]).
> ByteBuffer cleanup

- src/misc/thread.h
- testApp/misc/testThread.cpp
Thread::Config has a named parameters style allowing method chaining to create a Thread with certain parameters and without the need to derive from epicsThreadRunnable.  It also makes it easy to give a meaningful name (pvAccess needs work here).
```
using namespace epics::pvData;
klass *K = ...;
Thread foo(Thread::Config(K, &klass::meth)
.prio(epicsThreadPriorityMedium)
<<"test"<<2
);
```
Creates a thread named "test2" where the thread main is a class method.  Also works with epicsThreadRunnable subclasses, and C void(*)(void*) + void*.
If not specified, priority defaults to epicsThreadPriorityLow, stack size to epicsThreadStackSmall, and autostart to true (in keeping with the other Thread constructors).
> new Thread::Config

- configure/CONFIG_SITE
- src/Makefile
Include the module version in the SONAME ("libpvData.so.5.0" atm.).  pvData_LIBS is already being set correctly w/ libCom.  Others are added by Base/gcc.
> $ readelf -d lib/linux-x86_64-debug/libpvData.so |egrep 'NEEDED|SONAME'
>  0x0000000000000001 (NEEDED)             Shared library: [libCom.so.3.16.0]
>  0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
>  0x0000000000000001 (NEEDED)             Shared library: [libreadline.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
>  0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
>  0x0000000000000001 (NEEDED) …
> set SHRLIB_VERSION for libpvData.so

- src/copy/pvCopy.cpp
- src/factory/StandardPVField.cpp
- src/pvMisc/bitSetUtil.cpp
Fix a couple of instances where the return values of getSubField() is dereferenced w/o checking for NULL.  Also close a logic hole in pvCopy.
@mrkraimer I only make a cursory search for the most obvious cases where getSubField() is mis-used.  I strongly suspect that there are more in pvCopy.cpp which are masked by the use of utility functions.
> getSubField -> getSubFieldT to avoid potential NULL de-ref.

- src/misc/serialize.h
- src/misc/serializeHelper.cpp
- testApp/misc/testSerialization.cpp
serializeToVector() takes an arbitrary subclass of Serializable to do so, with the results placed in a byte array (vector<char>).  No type information caching is performed as the code to do this is presently in pvAccessCPP.
I wrote serializeToVector() for the new gateway to provide a key for a lookup table to de-duplicate requests having idential pvrequest blobs.  I was concerned that, while operator< could be implemented for PVStructure for use with key std::map, this wouldn't be efficient.  This would be the ideal situation for a hash table, but PVField sub-classes also doesn't define a hash function, and I can't easily use std::unordered_map anyway.
While this code began like as a workaround, I think it can function as a useful example of operating on Serialization.  If it isn't …
> add serializeToVector()

- src/misc/pv/sharedVector.h
- testApp/misc/testSharedVector.cpp
- testApp/pv/testPVScalarArray.cpp
Fix some issues w/ shared_vector<> resulting in compile errors.  Added test cases and documentation edits
1. Allow static_shared_vector_cast<>() no-op casts (eg. void -> void).  Was a compile error
1. freeze(shared_vector<void>&) failed to compile due to missing friend and typedef
1. freeze(shared_vector<void>&) would have lost the original type due to a missing initializer.  Masked by previous compile error.
> Fix shared_vector<>

- documentation/RELEASE_NOTES.html
- documentation/RELEASE_NOTES.md
- src/misc/bitSet.cpp
- testApp/misc/testBitSet.cpp
Commits for a 5.0.4 release which patches issues found since 5.0.3.
Adds the following fixes:
* Fixed bitset serialization (issue #24)
* Fixed truncation in BitSet::or_and (issue #27)
Contains cherry picks of commits  65ff7ab1c3d8a532472b39af40acaf3480008a8b, 336a8b3bc2fb7c3123756a8e93082dbe85ecfaee and d4292d81f2391a5bb5e5747f0f6ceacec028c1e2.
> Make release 5.0.4

- src/monitor/monitorPlugin.cpp
- src/monitor/pv/monitorPlugin.h
As far as I can see, MonitorPlugin and friends aren't used anywhere in pvDataCPP, pvAccessCPP, pvaSrv, or pvDatabaseCPP.  This appear to be an incomplete feature.  Unless there are, or will shortly be, user code I'd like to mark it deprecated for removal after the next feature release.
This file appears was added by 5e3159f8008c744b14c41204d68bdf864f32f80a preceding 3.1.0.
> Deprecate monitorPlugin.h

- src/misc/bitSet.cpp
- src/misc/pv/bitSet.h
- testApp/misc/testBitSet.cpp
Use std::vector to manage storage instead of raw array. Make some global variable "constants" into macros so they can be inlined. Add swap() method.
Resumption of #22
> bitSet: macros and vector storage

- src/factory/FieldCreateFactory.cpp
- src/factory/PVDataCreateFactory.cpp
- src/misc/epicsException.cpp
- src/misc/parseToPOD.cpp
- src/misc/pv/byteBuffer.h
- src/misc/pv/epicsException.h
- src/misc/pv/sharedPtr.h
- src/misc/pv/sharedVector.h
- src/misc/timer.cpp
- src/pv/pvData.h
- src/pv/pvType.h
- testApp/misc/testBitSet.cpp
- testApp/misc/testSerialization.cpp
- testApp/misc/testTypeCast.cpp
These changes allow pvDataCPP to be built for the Cygwin and MinGW targets, including cross-compiling for MinGW on Linux. A few other minor cleanups are included as well.
> Support for additional Windows targets

- src/misc/pv/requester.h
- src/misc/requester.cpp
Provide a default implementation of Requester::message() which does what most sub-classes do anyway, which is print to std::cerr.  Lets prepare to remove some boilerplate!
> Default implementation for Requester::message()

- src/factory/PVStructure.cpp
- src/pv/pvData.h
Template getSubField has overload for c-strings but not non-template version. Add for non-template. Improves performance when argument is string literal.
> Add char* overload for non-template getSubField

- src/copy/pvCopy.cpp
- testApp/copy/testCreateRequest.cpp
- testApp/copy/testPVCopy.cpp
- testApp/property/testProperty.cpp
- testApp/pv/testBitSetUtil.cpp
- testApp/pv/testPVData.cpp
Replace non-template getSubField with template version when PVField is of a known, derived type.
As per #34,but only do for derived classes. Avoid getSubField&lt;PVField&gt; as the dynamic_pointer_cast is not (as you might think) a null op. Especially avoid in the offset version as this can lead to several unnecessary pointer casts (see discussion in #34). In #34 there are sometimes more appropriate types for the template argument so use these.
> Replace template getSubField with template version

- src/misc/executor.cpp
My preferred solution to Peter Heesterman's issue #37
> Resolve github #37 without cacheing epicsExportSharedSymbols

- src/misc/pv/byteBuffer.h
- testApp/misc/testByteBuffer.cpp
Mainly cleanup and tests.  And change align()
align(n) now fills skipped bytes with '\0'.
align(n,f) to choose a different fill value.
No other changes intended
Use intrinsic byte order swapping builtins for gcc, clang, and msvc.
use assert() to check pre/post conditions.
Remove unused condition macros and unreachable code.
Add tests of byte swapping primitives and
test the correctness of unaligned operations.
add illustrations of flip() and rewind()
> overhaul byteBuffer implementation

- src/factory/Compare.cpp
- src/factory/FieldCreateFactory.cpp
- src/pv/pvIntrospect.h
- testApp/misc/testSerialization.cpp
- testApp/pv/Makefile
- testApp/pv/performstruct.cpp
- testApp/pv/testFieldBuilder.cpp
In an effort to make Field (aka type) comparison cheap, so that it can be done more often, use a global hash table to prevent duplicate instances of Field (and associated sub-classes).  ```operator==``` for Field becomes simple pointer comparison (the existing comparison is renamed to ```epics::pvData::compare()```).
This does make Field creation more expensive, but this is not something which a well behaved program should do frequently (after startup).
Hashing is done with the simple (though inefficient) expedient of applying ```epicsStrHash()``` to the output of ```operator<<```.
> Field instance de-duplication

- testApp/pv/Makefile
Fixes linker error:
/opt/eldk-5.2/powerpc-e500v2/sysroots/i686-eldk-linux/usr/bin/ppce500v2-linux-gnuspe/../../libexec/ppce500v2-linux-gnuspe/gcc/powerpc-linux-gnuspe/4.6.4/ld: performstruct.o: undefined reference to symbol 'clock_gettime@@GLIBC_2.2' 
/opt/eldk-5.2/powerpc-e500v2/sysroots/i686-eldk-linux/usr/bin/ppce500v2-linux-gnuspe/../../libexec/ppce500v2-linux-gnuspe/gcc/powerpc-linux-gnuspe/4.6.4/ld: note: 'clock_gettime@@GLIBC_2.2' is defined in DSO /opt/eldk-5.2/powerpc-e500v2/sysroots/ppce500v2-linux-gnuspe/lib/librt.so.1 so try adding it to the linker command line
> link with rt when using clock_gettime()

- src/copy/Makefile
- src/copy/pv/createRequest.h
- src/copy/requestmapper.cpp
- testApp/copy/testCreateRequest.cpp
Utility for pvRequest .field mangling in ChannelProvider implementations, either my or @mrkraimer preferred schemes can be selected with an enum.  As per #51 this API is intended as a replacement of pvCopy, and the simpler extractRequestMask() I added previously.
A ```PVRequestMapper``` holds a precomputed mapping between two Structures, referred to as "Base" and "Requested".
* Base - The internal structure manipulated by server/provider logic.
* Requested - The structure seen by user/client code.
The API itself revolves around the ```PVRequestMapper::copyBaseToRequested()``` and ```PVRequestMapper::copyBaseFromRequested()``` methods which allow masked shallow copying between PVStructures of the two types.
So a minimal usage would look like
```c++
// eg. during ChannelGet setup …
```
> add PVRequestMapper

- src/copy/createRequest.cpp
- src/copy/requestmapper.cpp
- src/factory/FieldCreateFactory.cpp
- src/pv/pvIntrospect.h
- src/pv/valueBuilder.cpp
- testApp/pv/testPVData.cpp
- testApp/pv/testPVStructureArray.cpp
Boilerplate reduction for using FieldBuilder and creating PVField instances.  Turns:
```c++
PVStructurePtr value(getPVDataCreate()->createPVStructure(getFieldCreate()->createFieldBuilder()
->add("a", pvInt)
->add("b", pvDouble)
->add("c", pvString)
->createStructure()));
```
into:
```c++
PVStructurePtr value(FieldBuilder::build()
->add("a", pvInt)
->add("b", pvDouble)
->add("c", pvString)
->createStructure()->create());
```
I've long been annoyed at how verbose Structure creation is.  Hearing @shroffk complaining about the same, and suggesting something like this has motivated me to do something about it.
>  Add FieldBuilder::build() and Field::create()

- src/factory/PVDataCreateFactory.cpp
- src/factory/printer.cpp
- src/misc/pv/typeCast.h
- src/pv/pvData.h
- testApp/misc/Makefile
- testApp/misc/testprinter.cpp
A work in progress which I don't have a hard timeline for merging.  At this point I'm hoping to identify a __minimal__ set of formating options.
This is a followup of my stated intent to formalize, and __simplify__, the output modes of the pvtools to get them into a state which I understand and am able to support.
My idea is that all options for controlling output format will flow through ```struct PVStructure::Formatter```, making clear the possible combinations for the purposes of testing.  This would include things like integer formatting (absent thus far).  I don't expect that all combinations will be tested.  This would be impractical.  I would like to test the important combinations (aka. defaults and things people complain about).
What this code does have is the idea of output …
> Add PVStructure::stream()

- src/misc/parseToPOD.cpp
The parseToPOD.cpp file defines strtoll and strtoull for EPICS Base < R3.15.0.1. This is not necessary with Visual Studio 2013+.
This is related to two prior, conflicting commits. The first, 587f81f5115ce5c785eff876c5b591eee352f98f, checks the version of _MSC_VER before defining strtoll and strtoull. The second, 50b82137813067d15227c3580ce18a287e096bbd, removes the check for _MSC_VER and tests only the version of EPICS base.
As far as I understand it, this should check against both _MSC_VER and the EPICS base version.
> Disabled NEED_OLL_FUNCS for Visual Studio 2013+

- src/json/print.cpp
- src/json/pv/json.h
- testApp/misc/testjson.cpp
Attempt to (mostly) fix #78 by adding another escaping dialect `epics::pvData::escape::JSON` which emits only the [specified](https://www.ecma-international.org/publications-and-standards/standards/ecma-404/) using `yajl_gen.h` from Base.
> fix JSON string escaping

- src/misc/pv/byteBuffer.h
Historically, `ByteBuffer` would use unaligned memory access.  This has caused problems before w/ PPC (#54 and #74).
I was under the impression that ARM/Linux would automatically handle unaligned access.  However, it appears (#84) that "fixup" logic is both incomplete, and conditional.  Incomplete in that some floating point instruction are not handled[1], and conditional[2] in that it can be switched on/off at runtime via `/proc/cpu/alignment`.
In the hope of avoiding further issues, this PR switches the `#if` logic to only use unaligned access on i386 and amd64 w/ GCC, clang, and MSVC.  The preprocessor macro names are selected with reference to my [usual first stop](https://sourceforge.net/p/predef/wiki/Architectures/), as well as some [MS …
> Change logic for selecting when to use unaligned access

- src/misc/debugPtr.cpp
- src/misc/pv/debugPtr.h
There are at least two changes to EPICS base since the addition of debugPtr:
* In pvAccess/**/dbdToPv.cpp, a write to an ostream was added (also in pvData/**/testSerialization.cpp) which does not resolve correctly when the operator<< overload is in the global namespace.
* In pvAccess/**/caChannel.cpp, weak_ptr->expired() was added
The interface to deal with each of these has been added.
Fixes https://github.com/epics-base/pvDataCPP/issues/88
> Update debugPtr to work with EPICS base 7.0.7

- src/factory/Convert.cpp
- src/misc/anyscalar.cpp
- src/misc/pv/anyscalar.h
- src/misc/reftrack.cpp
These were issues reported by clang-tidy as I was running that on epics-base.
* `AnyScalar::bufferUnsafe()` was returning a pointer to the data of an `std::string` living on the stack.
* `ostringstream::str()` returns `std::string` by value, so we can't keep a pointer to its data without first turning it into an lvalue.
* `split` should take the string as a reference to avoid unnecessary copies.
* Added `noexcept` to the move ctor/assignment of `AnyScalar`
> Fix a couple bugs

- testApp/pv/testOperators.cpp
A (non-functional trivial) change that silences/fixes an issue reported by cppcheck / sonar. Intended to make EPICS Base pass the ITER quality gates again.
- silence warning about uninitialized local variable
> Fix issue detected by cppcheck / sonarqube

- .appveyor.yml
> ci: consistent AppVeyor job config for pvData/pvAccess
